// web-react/src/pages/Timeline.js
import React, { Component } from 'react';
import twitterLogo from '../twitter.svg'
import './Timeline.css'
import api from '../services/api'
import Tweet from '../components/Tweet'
import socket from 'socket.io-client'

export default class Timeline extends Component {
  state = {
    tweets: [],
    newTweet: ''
  }

  async componentDidMount() {
    this.subscribeToEvents()
    const response = await api.get('tweets')
    this.setState({ tweets: response.data })
  }

  handleInputChange = (e) => {
    this.setState({ newTweet: e.target.value })
  }

  handleNewTweet = async e => {
    if (e.keyCode !== 13) return
    const content = this.state.newTweet
    const author = localStorage.getItem('@TwitterClone:username')
    
    await api.post('tweets', { content, author })
    this.setState({ newTweet: '' })
  }

  subscribeToEvents = () => {
    const io = socket('http://localhost:3000')
    io.on('tweet', data => {
      this.setState({ tweets: [data, ... this.state.tweets] })
    })
    io.on('like', data => {
      this.setState({ 
        tweets: this.state.tweets.map(tweet => 
          tweet._id === data._id ? data : tweet
      ) })
    })
  }

  render() {
    return (
      <div className="timeline-wrapper">
        <img src={twitterLogo} alt="TwitterLogo" height={24} />
        <form>
          <textarea value={this.state.newTweet}
            onChange={this.handleInputChange}
            onKeyDown={this.handleNewTweet}
            placeholder="O que está acontecendo?"
          />
        </form>
        <ul className="tweet-list">
          { this.state.tweets.map(tweet => (
            <Tweet key={tweet._id} tweet={tweet} />
          )) }
        </ul>
      </div>
    )
  }
}

// web-vue/src/views/Timeline.vue
<template>
  <div class="timeline-wrapper">
    <img src="../assets/twitter.svg" alt="TwitterLogo" height="24">
    <form>
      <textarea
       placeholder="O que está acontecendo?" 
       v-model="newTweet"
       @keyup.enter="onNewTweet"/>
    </form>
    <li class="tweet-list">
      <Tweet
        :tweet="tweet"
        v-for="tweet in tweets"
        :key="tweet._id"
      />
    </li>
  </div>
</template>
<script>
import Tweet from '@/components/Tweet.vue'
import api from '@/services/api'

export default {
  name: 'Timeline',
  components: { Tweet },
  data() {
    return {
      tweets: [],
      newTweet: ''
    }
  },
  async mounted() {
    const response = await api.get('tweets')
    this.tweets = response.data
  },
  sockets: {
    tweet(data) {
      this.tweets = [data, ...this.tweets]
    },
    like(data) {
      this.tweets = this.tweets.map(tweet => tweet._id === data._id ? data : tweet)
    }    
  },
  methods: {
    async onNewTweet() {
      const content = this.newTweet
      const author = localStorage.getItem('@TwitterCloneVue:username')
      await api.post('tweets', { content, author })
      this.newTweet = ''
    }
  }
}
</script>
<style>
.timeline-wrapper {
  width: 600px;
  margin: 50px auto;

  display: flex;
  flex-direction: column;
  align-items: stretch;
}

.timeline-wrapper form {
  width: 100%;
  background: #e9f1f6;
  padding: 20px;
  border-radius: 5px;
  margin: 30px 0;
}

.timeline-wrapper form textarea {
  border: 3px solid #d8e5ed;
  border-radius: 5px;
  font-size: 14px;
  padding: 15px;
  width: 100%;
  resize: none;
}

.tweet-list {
  list-style: none;
  color: #1c2022;
}
</style>
